[[plugins]]
package = "/plugins/@iteria-netlify-plugin"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
